### ISSUE TITLE
Incorrect parameter passed into explode if SimpleArrayType column is used

### ISSUE THREAD

**Issue by javabudd** [API-Skeletons/zf-doctrine-module-zend-hydrator#6]
Version 1.0.1

I have defined a field called `emails` on my entity.

`@ORM\Column(name="emails", type="simple_array", nullable=true)`

Due to the recent changes of `handleTypeConversions`, $value is now retrieved as an array and passed into convertToPHPValue for the SimpleArrayType, which then errors when calling explode(',' $value) because the 2nd parameters is expected to be a string.

To fix this, I have updated my tests to send a comma delimited string to the endpoint instead of an array, but this is not technically correct because we pass arrays in production

**Comment by javabudd** [comment]
stacktrace:

`
{"trace":[{"function":"errorHandler","class":"Codeception\\Subscriber\\ErrorHandler","type":"->","args":[2,"explode() expects parameter 2 to be string, array given","vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/SimpleArrayType.php",69,{"value":["foo4@example.com"],"platform":{}}]},{"file":"vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/SimpleArrayType.php","line":69,"function":"explode","args":[",",["foo4@example.com"]]},{"file":"vendor/api-skeletons/zf-doctrine-module-zend-hydrator/src/DoctrineObject.php","line":502,"function":"convertToPHPValue","class":"Doctrine\\DBAL\\Types\\SimpleArrayType","type":"->","args":[["foo4@example.com"],{}]},{"file":"vendor/api-skeletons/zf-doctrine-module-zend-hydrator/src/DoctrineObject.php","line":255,"function":"handleTypeConversions","class":"DoctrineModule\\Stdlib\\Hydrator\\DoctrineObject","type":"->","args":[["foo4@example.com"],"simple_array"]},{"file":"vendor/api-skeletons/zf-doctrine-module-zend-hydrator/src/DoctrineObject.php","line":106,"function":"hydrateByValue","class":"DoctrineModule\\Stdlib\\Hydrator\\DoctrineObject","type":"->",
`

**Comment by TomHAnderson** [comment]
The original code did not try to process your simple_array typed field: https://github.com/API-Skeletons/zf-doctrine-module-zend-hydrator/commit/785463984d1fc7ae6b409b12cae6ec03ebafbb0e#diff-9de7c72af35344f6413ef517d7ab2906R492

This was in error because it also did not try to process any custom type field: https://blog.tomhanderson.com/2018/09/datetime-with-microseconds-for-mysql-in.html

For simple_array: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/SimpleArrayType.php
converting from a hydrator value to a PHP value expects a string.  This is because of the nature of simple_array.  It stores values as a comma delimited string.  The input for simple_array is a string and the output is an array.  It sounds like you are improperly sending an array as input; and that is wrong for the simple_array type.

I think your best solution at this point is to create your own custom type which can take an array as input.  The article linked for microseconds gives an example of how to create a custom type.  If you choose not to do this you can create your own hydrator to replace your use of DoctrineObject but if you're using Doctrine in Apigility then the code which gets the hydrator from the service manager uses `get()` and not `build()` so you must create a separate service manager entry for each hydrator.

In making the hydrator change I created a more technically correct hydrator.  Because your use of simple_array was not as technically correct do you see this error.

**Comment by TomHAnderson** [comment]
As an alternative you could lock your composer at 1.0.0

**Comment by javabudd** [comment]
I have chosen for now to lock composer at 1.0.0 and will play around with some different implementations. Thanks for the help
